Fix: add symlinks in /usr for compatibility again (#17)
osquery/osquery-packaging pull request #18
Opened 2021-10-18 14:11 UTC by thomas-merz

This change re-introduces some symlinks in /usr that [have existed before 5.0](https://github.com/osquery/osquery-packaging/pull/13) and [are missing on some Enterprise Linux distributions](https://github.com/osquery/osquery-packaging/issues/17).

2021-10-19 14:13 UTC, directionless commented
I think this is going to need to also create the symlinks. And that we should stop creating /usr/local ones. 

@sharvilshah ?

2021-10-19 14:58 UTC, sharvilshah requested changes
Hello @thomas-merz, thanks for taking this on!

As @directionless mentioned, this won't create the symlinks. In fact `${OSQUERY_DATA_PATH}/usr/local/bin/osquery...` may not even be present. 

Can you take a look at the example in this file where we create symlinks further down? 
After that, it would also need to be "installed"

2021-10-19 15:50 UTC, thomas-merz commented
@sharvilshah , I really don't understand in detail what I'm doing here due to lack of knowledge/understanding of this CMAKE thing… 😖 But hopefully this change will create three symlinks in `/usr/local/bin` to the corresponding file(s) in `/opt/osquery/bin` and "install" them 🤷‍♂️

2021-11-09 16:37 UTC, thomas-merz commented
@sharvilshah , did you find some time to review my PR or should I ask/trigger any of the "6 pending reviewers" directly?

2021-11-30 17:45 UTC, Smjert commented
Hello @thomas-merz, thank you for this PR!

I took the liberty to fix a couple of things since what we wanted was to have the symlink installed under  `/usr/bin` and not `/usr/local/bin`.
I've also left the addition of the link to `osqueryd` (mind though that only Linux right now will have this, macOS doesn't).

2021-11-30 22:02 UTC, thomas-merz commented
Hello @Smjert , I'm fine with your changes and corrections. But with my change, fetch of upstream and (force-)push again into my fork your change/commit is "gone" now 😢

2021-11-30 22:11 UTC, thomas-merz commented
I "found" your commit and adopted it manually. I hope this is ok the way I did it!?

2021-12-02 13:43 UTC, Smjert commented on platform/linux/common.cmake
> +    "/usr//bin/"
There's a double slash here, should be `/usr/bin`.

2021-12-02 13:47 UTC, Smjert commented
> I "found" your commit and adopted it manually. I hope this is ok the way I did it!?
We normally work with the rebase workflow. If you want to realign the branch to the master branch, do not use `git pull` unless it's configured in the repo to avoid merges via `git config merge.ff only`.
Otherwise I normally use `git rebase -i master`, so that's interactive and you can see which commits are additionally put on top of master.

2021-12-02 21:14 UTC, Smjert approved these changes

2021-12-02 21:15 UTC, merged